### ISSUE TITLE
 error: ‘HTSCODECS_VERSION_TEXT’ undeclared

### ISSUE THREAD

**Issue by diegohernansanchez** [ANGSD/angsd#478]
Hi,
Im trying to install ANGSD following:
cd htslib;make;cd ..
cd angsd
make HTSSRC=../htslib

But I get this error:
htscodecs/htscodecs/htscodecs.c: In function ‘htscodecs_version’:
htscodecs/htscodecs/htscodecs.c:43:12: error: ‘HTSCODECS_VERSION_TEXT’ undeclared (first use in this function)
     return HTSCODECS_VERSION_TEXT;
            ^
htscodecs/htscodecs/htscodecs.c:43:12: note: each undeclared identifier is reported only once for each function it appears in
htscodecs/htscodecs/htscodecs.c:44:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:164: recipe for target 'htscodecs/htscodecs/htscodecs.o' failed
make: *** [htscodecs/htscodecs/htscodecs.o] Error 1

No idea what it means, but Im using Ubuntu 16 ... perhaps due to the older Ubuntu version? Which ANGSD should I use?
Thanks, sorry for silly question.
Best
d!!!

**Comment by OliverPStuart** [comment]
Hi Diego,
I'm having this problem too. Did you find a solution?
Ollie

**Comment by isinaltinkaya** [comment]
It looks like an issue regarding the htslib installation. Can you try using the htslib submodule?

```
git clone https://github.com/angsd/angsd.git;
cd angsd; make
```

**Comment by diegohernansanchez** [comment]
Hi,
This is what I did at the very begging, resulting in error. I also tried downloading the binaries, with no avail. As a result, I found that the newest version that works in my Ubuntu 16 is the 0.920. Any version after that one gives errors with the htslib, although the htslib folder is generated during installation.
Thanks. 
d!!!

**Comment by ANGSD** [comment]
Dear all, the software installs using workflow and locally on my system so I assume it is your local system. Could you try to pull the newest version of htslib and angsd and do make clean;make. For htslib first and then angsd.

Best

**Comment by isinaltinkaya** [comment]
Hi all,

Following these steps should resolve the issue for angsd 0.934 and 0.936 installations:

```
cd htslib; echo '#define HTSCODECS_VERSION_TEXT "1.0"' > htscodecs/htscodecs/version.h; make;
```


Best,
Isin

**Comment by isinaltinkaya** [comment]
Related to htslib_#1346 and htscodecs_#50.

Issue is fixed with the new tarballs.

The new tarballs can also be found at:
https://github.com/ANGSD/angsd/releases/download/0.936/angsd0.936.tar.gz
https://github.com/ANGSD/angsd/releases/download/0.934/angsd0.934.tar.gz

Best,
Isin
